#!/usr/bin/env python3
"""
Translate resource files for Melodee.Blazor
This script reads the base English resource file and creates/updates translated versions.
"""

import xml.etree.ElementTree as ET
from pathlib import Path
import html

# Translation dictionaries for each language
# Key: English value, Value: Translated value

GERMAN_TRANSLATIONS = {
    # Navigation
    "Dashboard": "Übersicht",
    "Library": "Bibliothek",
    "Artists": "Künstler",
    "Albums": "Alben",
    "Songs": "Titel",
    "Playlists": "Wiedergabelisten",
    "Radio Stations": "Radiosender",
    "Charts": "Charts",
    "Requests": "Anfragen",
    "Now Playing": "Wird gerade gespielt",
    "Statistics": "Statistiken",
    "Search": "Suchen",
    "Settings": "Einstellungen",
    "Admin": "Administration",
    "Jobs": "Aufgaben",
    "Users": "Benutzer",
    "System Settings": "Systemeinstellungen",
    "Account": "Konto",
    "Profile": "Profil",
    "Logout": "Abmelden",
    "Libraries": "Bibliotheken",
    "Shares": "Freigaben",
    "About": "Über",
    "Media": "Medien",
    "Media Artists": "Medienkünstler",
    "Stats": "Statistiken",
    "About Me": "Über mich",
    
    # Common
    "Name": "Name",
    "Description": "Beschreibung",
    "Status": "Status",
    "Type": "Typ",
    "Created": "Erstellt",
    "Modified": "Geändert",
    "Actions": "Aktionen",
    "Yes": "Ja",
    "No": "Nein",
    "None": "Keine",
    "All": "Alle",
    "Loading...": "Wird geladen...",
    "Error": "Fehler",
    "Success": "Erfolg",
    "Warning": "Warnung",
    "Info": "Information",
    "Confirm": "Bestätigen",
    "Total": "Gesamt",
    "Count": "Anzahl",
    "Size": "Größe",
    "Duration": "Dauer",
    "Date": "Datum",
    "Time": "Zeit",
    "Year": "Jahr",
    "Month": "Monat",
    "Day": "Tag",
    "Hour": "Stunde",
    "Minute": "Minute",
    "Second": "Sekunde",
    "Title": "Titel",
    "Artist": "Künstler",
    "Album": "Album",
    "Genre": "Genre",
    "Track": "Titel",
    "Tracks": "Titel",
    "Play": "Abspielen",
    "Pause": "Pause",
    "Stop": "Stopp",
    "Previous": "Zurück",
    "Next": "Weiter",
    "Shuffle": "Zufällig",
    "Repeat": "Wiederholen",
    "Volume": "Lautstärke",
    "Mute": "Stumm",
    "Rating": "Bewertung",
    "Favorite": "Favorit",
    "Favorites": "Favoriten",
    "Queue": "Warteschlange",
    "History": "Verlauf",
    "Recent": "Kürzlich",
    "Popular": "Beliebt",
    "New": "Neu",
    "Top": "Top",
    "Random": "Zufällig",
    "Filter": "Filter",
    "Sort": "Sortieren",
    "Sort By": "Sortieren nach",
    "Order": "Reihenfolge",
    "Ascending": "Aufsteigend",
    "Descending": "Absteigend",
    "Page": "Seite",
    "of": "von",
    "Items": "Einträge",
    "per page": "pro Seite",
    "Selected": "Ausgewählt",
    "Select All": "Alle auswählen",
    "Deselect All": "Alle abwählen",
    "Details": "Details",
    "View": "Ansehen",
    "Edit": "Bearbeiten",
    "Delete": "Löschen",
    "Add": "Hinzufügen",
    "Remove": "Entfernen",
    "Create": "Erstellen",
    "Update": "Aktualisieren",
    "Save": "Speichern",
    "Cancel": "Abbrechen",
    "Close": "Schließen",
    "Apply": "Anwenden",
    "Reset": "Zurücksetzen",
    "Clear": "Löschen",
    "Refresh": "Aktualisieren",
    "Reload": "Neu laden",
    "Download": "Herunterladen",
    "Upload": "Hochladen",
    "Import": "Importieren",
    "Export": "Exportieren",
    "Copy": "Kopieren",
    "Paste": "Einfügen",
    "Cut": "Ausschneiden",
    "Undo": "Rückgängig",
    "Redo": "Wiederholen",
    "Help": "Hilfe",
    "Options": "Optionen",
    "More": "Mehr",
    "Less": "Weniger",
    "Show": "Anzeigen",
    "Hide": "Verbergen",
    "Enable": "Aktivieren",
    "Disable": "Deaktivieren",
    "Enabled": "Aktiviert",
    "Disabled": "Deaktiviert",
    "Active": "Aktiv",
    "Inactive": "Inaktiv",
    "Online": "Online",
    "Offline": "Offline",
    "Available": "Verfügbar",
    "Unavailable": "Nicht verfügbar",
    "Public": "Öffentlich",
    "Private": "Privat",
    "Shared": "Geteilt",
    "Locked": "Gesperrt",
    "Unlocked": "Entsperrt",
    "Required": "Erforderlich",
    "Optional": "Optional",
    "Default": "Standard",
    "Custom": "Benutzerdefiniert",
    "Advanced": "Erweitert",
    "Basic": "Grundlegend",
    "General": "Allgemein",
    "Specific": "Spezifisch",
    "Unknown": "Unbekannt",
    "Other": "Andere",
    "N/A": "N/V",
    
    # Actions
    "Save Changes": "Änderungen speichern",
    "Saved successfully": "Erfolgreich gespeichert",
    "Deleted successfully": "Erfolgreich gelöscht",
    "Updated successfully": "Erfolgreich aktualisiert",
    "Created successfully": "Erfolgreich erstellt",
    "Failed to save": "Speichern fehlgeschlagen",
    "Failed to delete": "Löschen fehlgeschlagen",
    "Failed to update": "Aktualisieren fehlgeschlagen",
    "Failed to create": "Erstellen fehlgeschlagen",
    "Are you sure?": "Sind Sie sicher?",
    "This action cannot be undone.": "Diese Aktion kann nicht rückgängig gemacht werden.",
    "Confirm Delete": "Löschen bestätigen",
    "Confirm Action": "Aktion bestätigen",
    "Processing...": "Wird verarbeitet...",
    "Please wait...": "Bitte warten...",
    "Operation completed": "Vorgang abgeschlossen",
    "Operation failed": "Vorgang fehlgeschlagen",
    "Back": "Zurück",
    "Submit": "Absenden",
    
    # Forms
    "Username": "Benutzername",
    "Password": "Passwort",
    "Email": "E-Mail",
    "First Name": "Vorname",
    "Last Name": "Nachname",
    "Phone": "Telefon",
    "Address": "Adresse",
    "City": "Stadt",
    "Country": "Land",
    "Postal Code": "Postleitzahl",
    "Comment": "Kommentar",
    "Comments": "Kommentare",
    "Notes": "Notizen",
    "Tags": "Tags",
    "Category": "Kategorie",
    "Categories": "Kategorien",
    "Label": "Label",
    "Value": "Wert",
    "Key": "Schlüssel",
    "Enter": "Eingeben",
    "Select": "Auswählen",
    "Choose": "Wählen",
    "Browse": "Durchsuchen",
    "File": "Datei",
    "Files": "Dateien",
    "Folder": "Ordner",
    "Path": "Pfad",
    "URL": "URL",
    "Link": "Link",
    "Image": "Bild",
    "Images": "Bilder",
    "Photo": "Foto",
    "Video": "Video",
    "Audio": "Audio",
    "Document": "Dokument",
    "Attachment": "Anhang",
    "Attachments": "Anhänge",
    
    # Validation
    "Required field": "Pflichtfeld",
    "Invalid format": "Ungültiges Format",
    "Invalid email": "Ungültige E-Mail",
    "Invalid URL": "Ungültige URL",
    "Too short": "Zu kurz",
    "Too long": "Zu lang",
    "Minimum": "Minimum",
    "Maximum": "Maximum",
    "Password mismatch": "Passwörter stimmen nicht überein",
    "Field required": "Feld erforderlich",
    
    # Messages
    "No results found": "Keine Ergebnisse gefunden",
    "No items found": "Keine Einträge gefunden",
    "No data available": "Keine Daten verfügbar",
    "Empty": "Leer",
    "Not found": "Nicht gefunden",
    "Access denied": "Zugriff verweigert",
    "Permission denied": "Berechtigung verweigert",
    "Session expired": "Sitzung abgelaufen",
    "Connection error": "Verbindungsfehler",
    "Server error": "Serverfehler",
    "Network error": "Netzwerkfehler",
    "Timeout": "Zeitüberschreitung",
    "Invalid request": "Ungültige Anfrage",
    "Invalid response": "Ungültige Antwort",
    "An error occurred": "Ein Fehler ist aufgetreten",
    "Something went wrong": "Etwas ist schiefgelaufen",
    "Try again": "Erneut versuchen",
    "Try again later": "Später erneut versuchen",
    "Contact support": "Support kontaktieren",
    
    # User
    "Login": "Anmelden",
    "Logout": "Abmelden",
    "Register": "Registrieren",
    "Sign In": "Anmelden",
    "Sign Out": "Abmelden",
    "Sign Up": "Registrieren",
    "Forgot Password": "Passwort vergessen",
    "Reset Password": "Passwort zurücksetzen",
    "Change Password": "Passwort ändern",
    "Current Password": "Aktuelles Passwort",
    "New Password": "Neues Passwort",
    "Confirm Password": "Passwort bestätigen",
    "Remember Me": "Angemeldet bleiben",
    "Stay logged in": "Eingeloggt bleiben",
    "Welcome": "Willkommen",
    "Hello": "Hallo",
    "Good morning": "Guten Morgen",
    "Good afternoon": "Guten Tag",
    "Good evening": "Guten Abend",
    "Goodbye": "Auf Wiedersehen",
    
    # Admin
    "Administration": "Administration",
    "Dashboard": "Übersicht",
    "Overview": "Übersicht",
    "Summary": "Zusammenfassung",
    "Report": "Bericht",
    "Reports": "Berichte",
    "Analytics": "Analysen",
    "Monitoring": "Überwachung",
    "Logs": "Protokolle",
    "Activity": "Aktivität",
    "Audit": "Prüfung",
    "System": "System",
    "Configuration": "Konfiguration",
    "Preferences": "Einstellungen",
    "Permissions": "Berechtigungen",
    "Roles": "Rollen",
    "Role": "Rolle",
    "Groups": "Gruppen",
    "Group": "Gruppe",
    "Members": "Mitglieder",
    "Member": "Mitglied",
    "Administrator": "Administrator",
    "User": "Benutzer",
    "Guest": "Gast",
    "Moderator": "Moderator",
    "Editor": "Redakteur",
    "Viewer": "Betrachter",
    
    # Music specific
    "Playlist": "Wiedergabeliste",
    "Add to Playlist": "Zur Wiedergabeliste hinzufügen",
    "Create Playlist": "Wiedergabeliste erstellen",
    "Remove from Playlist": "Aus Wiedergabeliste entfernen",
    "Play Now": "Jetzt abspielen",
    "Play Next": "Als nächstes abspielen",
    "Add to Queue": "Zur Warteschlange hinzufügen",
    "Clear Queue": "Warteschlange leeren",
    "Now Playing": "Wird gespielt",
    "Up Next": "Als nächstes",
    "Recently Played": "Kürzlich gespielt",
    "Most Played": "Am meisten gespielt",
    "Top Rated": "Bestbewertet",
    "New Releases": "Neuerscheinungen",
    "Album Artist": "Albumkünstler",
    "Track Number": "Titelnummer",
    "Disc Number": "CD-Nummer",
    "Release Date": "Erscheinungsdatum",
    "Play Count": "Wiedergaben",
    "Last Played": "Zuletzt gespielt",
    "Bitrate": "Bitrate",
    "Sample Rate": "Abtastrate",
    "Channels": "Kanäle",
    "Format": "Format",
    "Codec": "Codec",
    "Quality": "Qualität",
    "High Quality": "Hohe Qualität",
    "Standard Quality": "Standardqualität",
    "Low Quality": "Niedrige Qualität",
    "Lyrics": "Liedtext",
    "Biography": "Biografie",
    "Discography": "Diskografie",
    "Similar Artists": "Ähnliche Künstler",
    "Related Albums": "Verwandte Alben",
    "Appears On": "Erscheint auf",
    "Compilations": "Zusammenstellungen",
    "Singles": "Singles",
    "EPs": "EPs",
    "Live Albums": "Live-Alben",
    "Soundtracks": "Soundtracks",
    "Various Artists": "Verschiedene Künstler",
    "Unknown Artist": "Unbekannter Künstler",
    "Unknown Album": "Unbekanntes Album",
    
    # Dashboard specific
    "Your plays (last 30 days)": "Ihre Wiedergaben (letzte 30 Tage)",
    "Your plays per day (last 30d)": "Ihre Wiedergaben pro Tag (letzte 30 Tage)",
    "Recent Activity": "Letzte Aktivität",
    "Quick Stats": "Kurzstatistik",
    "Total Albums": "Alben gesamt",
    "Total Artists": "Künstler gesamt",
    "Total Songs": "Titel gesamt",
    "Total Plays": "Wiedergaben gesamt",
    "Total Duration": "Gesamtdauer",
    "Storage Used": "Verwendeter Speicher",
    "Last Updated": "Zuletzt aktualisiert",
    "System Health": "Systemzustand",
    "Server Status": "Serverstatus",
    "Database Status": "Datenbankstatus",
    "Online Users": "Online-Benutzer",
    "Active Sessions": "Aktive Sitzungen",
    
    # Job related
    "Job": "Aufgabe",
    "Job Name": "Aufgabenname",
    "Job Status": "Aufgabenstatus",
    "Running": "Wird ausgeführt",
    "Completed": "Abgeschlossen",
    "Failed": "Fehlgeschlagen",
    "Pending": "Ausstehend",
    "Cancelled": "Abgebrochen",
    "Scheduled": "Geplant",
    "Last Run": "Letzte Ausführung",
    "Next Run": "Nächste Ausführung",
    "Start Time": "Startzeit",
    "End Time": "Endzeit",
    "Execution Time": "Ausführungszeit",
    "Progress": "Fortschritt",
    "Trigger Job": "Aufgabe auslösen",
    "Pause Job": "Aufgabe pausieren",
    "Resume Job": "Aufgabe fortsetzen",
    "Cancel Job": "Aufgabe abbrechen",
    "View Logs": "Protokolle anzeigen",
    
    # Library related
    "Scan Library": "Bibliothek scannen",
    "Rescan Library": "Bibliothek neu scannen",
    "Update Library": "Bibliothek aktualisieren",
    "Library Path": "Bibliothekspfad",
    "Library Name": "Bibliotheksname",
    "Library Type": "Bibliothekstyp",
    "Music Library": "Musikbibliothek",
    "Media Library": "Medienbibliothek",
    "Last Scan": "Letzter Scan",
    "Items in Library": "Einträge in Bibliothek",
    "Add Library": "Bibliothek hinzufügen",
    "Remove Library": "Bibliothek entfernen",
    "Edit Library": "Bibliothek bearbeiten",
    
    # Misc
    "Version": "Version",
    "Build": "Build",
    "Release": "Release",
    "License": "Lizenz",
    "Copyright": "Urheberrecht",
    "Privacy Policy": "Datenschutzerklärung",
    "Terms of Service": "Nutzungsbedingungen",
    "Documentation": "Dokumentation",
    "API": "API",
    "Support": "Support",
    "Feedback": "Feedback",
    "Report Bug": "Fehler melden",
    "Feature Request": "Funktionswunsch",
    "Changelog": "Änderungsprotokoll",
    "What's New": "Neuigkeiten",
    
    # Ok status
    "Ok": "OK",
    "OK": "OK",
    "ok": "OK",
    
    # you are admin/editor
    "You are an Admin!": "Sie sind ein Administrator!",
    "You are an Editor!": "Sie sind ein Redakteur!",
}

ITALIAN_TRANSLATIONS = {
    # Navigation
    "Dashboard": "Pannello di controllo",
    "Library": "Libreria",
    "Artists": "Artisti",
    "Albums": "Album",
    "Songs": "Brani",
    "Playlists": "Playlist",
    "Radio Stations": "Stazioni radio",
    "Charts": "Classifiche",
    "Requests": "Richieste",
    "Now Playing": "In riproduzione",
    "Statistics": "Statistiche",
    "Search": "Cerca",
    "Settings": "Impostazioni",
    "Admin": "Amministrazione",
    "Jobs": "Attività",
    "Users": "Utenti",
    "System Settings": "Impostazioni di sistema",
    "Account": "Account",
    "Profile": "Profilo",
    "Logout": "Esci",
    "Libraries": "Librerie",
    "Shares": "Condivisioni",
    "About": "Informazioni",
    "Media": "Media",
    "Media Artists": "Artisti multimediali",
    "Stats": "Statistiche",
    "About Me": "Su di me",
    
    # Common
    "Name": "Nome",
    "Description": "Descrizione",
    "Status": "Stato",
    "Type": "Tipo",
    "Created": "Creato",
    "Modified": "Modificato",
    "Actions": "Azioni",
    "Yes": "Sì",
    "No": "No",
    "None": "Nessuno",
    "All": "Tutti",
    "Loading...": "Caricamento...",
    "Error": "Errore",
    "Success": "Successo",
    "Warning": "Avviso",
    "Info": "Informazione",
    "Confirm": "Conferma",
    "Total": "Totale",
    "Count": "Conteggio",
    "Size": "Dimensione",
    "Duration": "Durata",
    "Date": "Data",
    "Time": "Ora",
    "Year": "Anno",
    "Title": "Titolo",
    "Artist": "Artista",
    "Album": "Album",
    "Genre": "Genere",
    "Track": "Traccia",
    "Tracks": "Tracce",
    "Play": "Riproduci",
    "Pause": "Pausa",
    "Stop": "Ferma",
    "Previous": "Precedente",
    "Next": "Successivo",
    "Shuffle": "Casuale",
    "Repeat": "Ripeti",
    "Volume": "Volume",
    "Rating": "Valutazione",
    "Favorite": "Preferito",
    "Favorites": "Preferiti",
    "Queue": "Coda",
    "History": "Cronologia",
    "Recent": "Recenti",
    "Popular": "Popolari",
    "New": "Nuovo",
    "Filter": "Filtra",
    "Sort": "Ordina",
    "Sort By": "Ordina per",
    "Details": "Dettagli",
    "View": "Visualizza",
    "Edit": "Modifica",
    "Delete": "Elimina",
    "Add": "Aggiungi",
    "Remove": "Rimuovi",
    "Create": "Crea",
    "Update": "Aggiorna",
    "Save": "Salva",
    "Cancel": "Annulla",
    "Close": "Chiudi",
    "Apply": "Applica",
    "Reset": "Reimposta",
    "Clear": "Cancella",
    "Refresh": "Aggiorna",
    "Download": "Scarica",
    "Upload": "Carica",
    "Import": "Importa",
    "Export": "Esporta",
    "Help": "Aiuto",
    "Options": "Opzioni",
    "More": "Altro",
    "Show": "Mostra",
    "Hide": "Nascondi",
    "Enable": "Abilita",
    "Disable": "Disabilita",
    "Enabled": "Abilitato",
    "Disabled": "Disabilitato",
    "Active": "Attivo",
    "Inactive": "Inattivo",
    "Online": "Online",
    "Offline": "Offline",
    "Available": "Disponibile",
    "Public": "Pubblico",
    "Private": "Privato",
    "Required": "Obbligatorio",
    "Optional": "Opzionale",
    "Default": "Predefinito",
    "Advanced": "Avanzato",
    "General": "Generale",
    "Unknown": "Sconosciuto",
    "Other": "Altro",
    
    # Actions
    "Save Changes": "Salva modifiche",
    "Saved successfully": "Salvato con successo",
    "Deleted successfully": "Eliminato con successo",
    "Updated successfully": "Aggiornato con successo",
    "Created successfully": "Creato con successo",
    "Failed to save": "Salvataggio fallito",
    "Failed to delete": "Eliminazione fallita",
    "Failed to update": "Aggiornamento fallito",
    "Failed to create": "Creazione fallita",
    "Are you sure?": "Sei sicuro?",
    "This action cannot be undone.": "Questa azione non può essere annullata.",
    "Confirm Delete": "Conferma eliminazione",
    "Confirm Action": "Conferma azione",
    "Processing...": "Elaborazione...",
    "Please wait...": "Attendere...",
    "Operation completed": "Operazione completata",
    "Operation failed": "Operazione fallita",
    "Back": "Indietro",
    "Submit": "Invia",
    
    # Forms
    "Username": "Nome utente",
    "Password": "Password",
    "Email": "Email",
    "Comment": "Commento",
    "Comments": "Commenti",
    "Tags": "Tag",
    "Category": "Categoria",
    "Value": "Valore",
    "Key": "Chiave",
    "Select": "Seleziona",
    "File": "File",
    "Files": "File",
    "Path": "Percorso",
    "Link": "Link",
    "Image": "Immagine",
    "Images": "Immagini",
    
    # Validation
    "Required field": "Campo obbligatorio",
    "Invalid format": "Formato non valido",
    "Invalid email": "Email non valida",
    "Field required": "Campo obbligatorio",
    
    # Messages
    "No results found": "Nessun risultato trovato",
    "No items found": "Nessun elemento trovato",
    "No data available": "Nessun dato disponibile",
    "Empty": "Vuoto",
    "Not found": "Non trovato",
    "Access denied": "Accesso negato",
    "An error occurred": "Si è verificato un errore",
    "Try again": "Riprova",
    
    # User
    "Login": "Accedi",
    "Logout": "Esci",
    "Register": "Registrati",
    "Sign In": "Accedi",
    "Sign Out": "Esci",
    "Sign Up": "Registrati",
    "Forgot Password": "Password dimenticata",
    "Reset Password": "Reimposta password",
    "Change Password": "Cambia password",
    "Current Password": "Password attuale",
    "New Password": "Nuova password",
    "Confirm Password": "Conferma password",
    "Welcome": "Benvenuto",
    
    # Admin
    "Administration": "Amministrazione",
    "Overview": "Panoramica",
    "Summary": "Riepilogo",
    "Report": "Rapporto",
    "Reports": "Rapporti",
    "Logs": "Log",
    "Activity": "Attività",
    "System": "Sistema",
    "Configuration": "Configurazione",
    "Preferences": "Preferenze",
    "Permissions": "Permessi",
    "Roles": "Ruoli",
    "Role": "Ruolo",
    "Administrator": "Amministratore",
    "User": "Utente",
    "Editor": "Editore",
    
    # Music specific
    "Playlist": "Playlist",
    "Add to Playlist": "Aggiungi alla playlist",
    "Create Playlist": "Crea playlist",
    "Play Now": "Riproduci ora",
    "Add to Queue": "Aggiungi alla coda",
    "Now Playing": "In riproduzione",
    "Recently Played": "Riprodotti di recente",
    "Most Played": "Più riprodotti",
    "Top Rated": "Più votati",
    "Album Artist": "Artista album",
    "Track Number": "Numero traccia",
    "Release Date": "Data di uscita",
    "Play Count": "Riproduzioni",
    "Last Played": "Ultima riproduzione",
    "Format": "Formato",
    "Quality": "Qualità",
    "Lyrics": "Testo",
    "Biography": "Biografia",
    "Similar Artists": "Artisti simili",
    "Unknown Artist": "Artista sconosciuto",
    "Unknown Album": "Album sconosciuto",
    
    # Dashboard specific
    "Your plays (last 30 days)": "Le tue riproduzioni (ultimi 30 giorni)",
    "Your plays per day (last 30d)": "Le tue riproduzioni al giorno (ultimi 30g)",
    "Recent Activity": "Attività recente",
    "Total Albums": "Album totali",
    "Total Artists": "Artisti totali",
    "Total Songs": "Brani totali",
    "Total Plays": "Riproduzioni totali",
    "Total Duration": "Durata totale",
    "Last Updated": "Ultimo aggiornamento",
    "Server Status": "Stato server",
    
    # Job related
    "Job": "Attività",
    "Job Name": "Nome attività",
    "Running": "In esecuzione",
    "Completed": "Completato",
    "Failed": "Fallito",
    "Pending": "In attesa",
    "Cancelled": "Annullato",
    "Scheduled": "Programmato",
    "Last Run": "Ultima esecuzione",
    "Next Run": "Prossima esecuzione",
    "Progress": "Progresso",
    
    # Library related
    "Scan Library": "Scansiona libreria",
    "Library Path": "Percorso libreria",
    "Library Name": "Nome libreria",
    "Music Library": "Libreria musicale",
    "Last Scan": "Ultima scansione",
    "Add Library": "Aggiungi libreria",
    "Edit Library": "Modifica libreria",
    
    # Misc
    "Version": "Versione",
    "License": "Licenza",
    "Documentation": "Documentazione",
    "Support": "Supporto",
    "Feedback": "Feedback",
    
    # Ok status
    "Ok": "OK",
    "OK": "OK",
    
    # you are admin/editor
    "You are an Admin!": "Sei un Amministratore!",
    "You are an Editor!": "Sei un Editore!",
}

JAPANESE_TRANSLATIONS = {
    # Navigation
    "Dashboard": "ダッシュボード",
    "Library": "ライブラリ",
    "Artists": "アーティスト",
    "Albums": "アルバム",
    "Songs": "曲",
    "Playlists": "プレイリスト",
    "Radio Stations": "ラジオ局",
    "Charts": "チャート",
    "Requests": "リクエスト",
    "Now Playing": "再生中",
    "Statistics": "統計",
    "Search": "検索",
    "Settings": "設定",
    "Admin": "管理",
    "Jobs": "ジョブ",
    "Users": "ユーザー",
    "System Settings": "システム設定",
    "Account": "アカウント",
    "Profile": "プロフィール",
    "Logout": "ログアウト",
    "Libraries": "ライブラリ",
    "Shares": "共有",
    "About": "概要",
    "Media": "メディア",
    "Media Artists": "メディアアーティスト",
    "Stats": "統計",
    "About Me": "自己紹介",
    
    # Common
    "Name": "名前",
    "Description": "説明",
    "Status": "ステータス",
    "Type": "タイプ",
    "Created": "作成日",
    "Modified": "更新日",
    "Actions": "アクション",
    "Yes": "はい",
    "No": "いいえ",
    "None": "なし",
    "All": "すべて",
    "Loading...": "読み込み中...",
    "Error": "エラー",
    "Success": "成功",
    "Warning": "警告",
    "Info": "情報",
    "Confirm": "確認",
    "Total": "合計",
    "Count": "件数",
    "Size": "サイズ",
    "Duration": "時間",
    "Date": "日付",
    "Time": "時刻",
    "Year": "年",
    "Title": "タイトル",
    "Artist": "アーティスト",
    "Album": "アルバム",
    "Genre": "ジャンル",
    "Track": "トラック",
    "Tracks": "トラック",
    "Play": "再生",
    "Pause": "一時停止",
    "Stop": "停止",
    "Previous": "前へ",
    "Next": "次へ",
    "Shuffle": "シャッフル",
    "Repeat": "リピート",
    "Volume": "音量",
    "Rating": "評価",
    "Favorite": "お気に入り",
    "Favorites": "お気に入り",
    "Queue": "キュー",
    "History": "履歴",
    "Recent": "最近",
    "Popular": "人気",
    "New": "新着",
    "Filter": "フィルター",
    "Sort": "並べ替え",
    "Sort By": "並べ替え",
    "Details": "詳細",
    "View": "表示",
    "Edit": "編集",
    "Delete": "削除",
    "Add": "追加",
    "Remove": "削除",
    "Create": "作成",
    "Update": "更新",
    "Save": "保存",
    "Cancel": "キャンセル",
    "Close": "閉じる",
    "Apply": "適用",
    "Reset": "リセット",
    "Clear": "クリア",
    "Refresh": "更新",
    "Download": "ダウンロード",
    "Upload": "アップロード",
    "Import": "インポート",
    "Export": "エクスポート",
    "Help": "ヘルプ",
    "Options": "オプション",
    "More": "もっと見る",
    "Show": "表示",
    "Hide": "非表示",
    "Enable": "有効",
    "Disable": "無効",
    "Enabled": "有効",
    "Disabled": "無効",
    "Active": "アクティブ",
    "Inactive": "非アクティブ",
    "Online": "オンライン",
    "Offline": "オフライン",
    "Available": "利用可能",
    "Public": "公開",
    "Private": "非公開",
    "Required": "必須",
    "Optional": "任意",
    "Default": "デフォルト",
    "Advanced": "詳細",
    "General": "一般",
    "Unknown": "不明",
    "Other": "その他",
    
    # Actions
    "Save Changes": "変更を保存",
    "Saved successfully": "保存しました",
    "Deleted successfully": "削除しました",
    "Updated successfully": "更新しました",
    "Created successfully": "作成しました",
    "Failed to save": "保存に失敗しました",
    "Failed to delete": "削除に失敗しました",
    "Failed to update": "更新に失敗しました",
    "Failed to create": "作成に失敗しました",
    "Are you sure?": "よろしいですか？",
    "This action cannot be undone.": "この操作は取り消せません。",
    "Confirm Delete": "削除の確認",
    "Confirm Action": "操作の確認",
    "Processing...": "処理中...",
    "Please wait...": "お待ちください...",
    "Operation completed": "操作が完了しました",
    "Operation failed": "操作に失敗しました",
    "Back": "戻る",
    "Submit": "送信",
    
    # Forms
    "Username": "ユーザー名",
    "Password": "パスワード",
    "Email": "メール",
    "Comment": "コメント",
    "Comments": "コメント",
    "Tags": "タグ",
    "Category": "カテゴリ",
    "Value": "値",
    "Key": "キー",
    "Select": "選択",
    "File": "ファイル",
    "Files": "ファイル",
    "Path": "パス",
    "Link": "リンク",
    "Image": "画像",
    "Images": "画像",
    
    # Validation
    "Required field": "必須項目",
    "Invalid format": "無効な形式",
    "Invalid email": "無効なメールアドレス",
    "Field required": "入力必須",
    
    # Messages
    "No results found": "結果が見つかりません",
    "No items found": "アイテムが見つかりません",
    "No data available": "データがありません",
    "Empty": "空",
    "Not found": "見つかりません",
    "Access denied": "アクセスが拒否されました",
    "An error occurred": "エラーが発生しました",
    "Try again": "再試行",
    
    # User
    "Login": "ログイン",
    "Logout": "ログアウト",
    "Register": "登録",
    "Sign In": "サインイン",
    "Sign Out": "サインアウト",
    "Sign Up": "サインアップ",
    "Forgot Password": "パスワードを忘れた",
    "Reset Password": "パスワードをリセット",
    "Change Password": "パスワードを変更",
    "Current Password": "現在のパスワード",
    "New Password": "新しいパスワード",
    "Confirm Password": "パスワードの確認",
    "Welcome": "ようこそ",
    
    # Admin
    "Administration": "管理",
    "Overview": "概要",
    "Summary": "要約",
    "Report": "レポート",
    "Reports": "レポート",
    "Logs": "ログ",
    "Activity": "アクティビティ",
    "System": "システム",
    "Configuration": "設定",
    "Preferences": "設定",
    "Permissions": "権限",
    "Roles": "ロール",
    "Role": "ロール",
    "Administrator": "管理者",
    "User": "ユーザー",
    "Editor": "編集者",
    
    # Music specific
    "Playlist": "プレイリスト",
    "Add to Playlist": "プレイリストに追加",
    "Create Playlist": "プレイリストを作成",
    "Play Now": "今すぐ再生",
    "Add to Queue": "キューに追加",
    "Now Playing": "再生中",
    "Recently Played": "最近再生した曲",
    "Most Played": "よく再生された曲",
    "Top Rated": "高評価",
    "Album Artist": "アルバムアーティスト",
    "Track Number": "トラック番号",
    "Release Date": "リリース日",
    "Play Count": "再生回数",
    "Last Played": "最終再生日",
    "Format": "形式",
    "Quality": "品質",
    "Lyrics": "歌詞",
    "Biography": "バイオグラフィ",
    "Similar Artists": "似たアーティスト",
    "Unknown Artist": "不明なアーティスト",
    "Unknown Album": "不明なアルバム",
    
    # Dashboard specific
    "Your plays (last 30 days)": "あなたの再生回数（過去30日）",
    "Your plays per day (last 30d)": "1日あたりの再生回数（過去30日）",
    "Recent Activity": "最近のアクティビティ",
    "Total Albums": "アルバム総数",
    "Total Artists": "アーティスト総数",
    "Total Songs": "曲の総数",
    "Total Plays": "総再生回数",
    "Total Duration": "合計時間",
    "Last Updated": "最終更新",
    "Server Status": "サーバーステータス",
    
    # Job related
    "Job": "ジョブ",
    "Job Name": "ジョブ名",
    "Running": "実行中",
    "Completed": "完了",
    "Failed": "失敗",
    "Pending": "保留中",
    "Cancelled": "キャンセル済み",
    "Scheduled": "スケジュール済み",
    "Last Run": "最終実行",
    "Next Run": "次回実行",
    "Progress": "進捗",
    
    # Library related
    "Scan Library": "ライブラリをスキャン",
    "Library Path": "ライブラリパス",
    "Library Name": "ライブラリ名",
    "Music Library": "音楽ライブラリ",
    "Last Scan": "最終スキャン",
    "Add Library": "ライブラリを追加",
    "Edit Library": "ライブラリを編集",
    
    # Misc
    "Version": "バージョン",
    "License": "ライセンス",
    "Documentation": "ドキュメント",
    "Support": "サポート",
    "Feedback": "フィードバック",
    
    # Ok status
    "Ok": "OK",
    "OK": "OK",
    
    # you are admin/editor
    "You are an Admin!": "あなたは管理者です！",
    "You are an Editor!": "あなたは編集者です！",
}

PORTUGUESE_TRANSLATIONS = {
    # Navigation
    "Dashboard": "Painel",
    "Library": "Biblioteca",
    "Artists": "Artistas",
    "Albums": "Álbuns",
    "Songs": "Músicas",
    "Playlists": "Playlists",
    "Radio Stations": "Estações de Rádio",
    "Charts": "Paradas",
    "Requests": "Solicitações",
    "Now Playing": "Reproduzindo Agora",
    "Statistics": "Estatísticas",
    "Search": "Buscar",
    "Settings": "Configurações",
    "Admin": "Administração",
    "Jobs": "Tarefas",
    "Users": "Usuários",
    "System Settings": "Configurações do Sistema",
    "Account": "Conta",
    "Profile": "Perfil",
    "Logout": "Sair",
    "Libraries": "Bibliotecas",
    "Shares": "Compartilhamentos",
    "About": "Sobre",
    "Media": "Mídia",
    "Media Artists": "Artistas de Mídia",
    "Stats": "Estatísticas",
    "About Me": "Sobre Mim",
    
    # Common
    "Name": "Nome",
    "Description": "Descrição",
    "Status": "Status",
    "Type": "Tipo",
    "Created": "Criado",
    "Modified": "Modificado",
    "Actions": "Ações",
    "Yes": "Sim",
    "No": "Não",
    "None": "Nenhum",
    "All": "Todos",
    "Loading...": "Carregando...",
    "Error": "Erro",
    "Success": "Sucesso",
    "Warning": "Aviso",
    "Info": "Informação",
    "Confirm": "Confirmar",
    "Total": "Total",
    "Count": "Contagem",
    "Size": "Tamanho",
    "Duration": "Duração",
    "Date": "Data",
    "Time": "Hora",
    "Year": "Ano",
    "Title": "Título",
    "Artist": "Artista",
    "Album": "Álbum",
    "Genre": "Gênero",
    "Track": "Faixa",
    "Tracks": "Faixas",
    "Play": "Reproduzir",
    "Pause": "Pausar",
    "Stop": "Parar",
    "Previous": "Anterior",
    "Next": "Próximo",
    "Shuffle": "Aleatório",
    "Repeat": "Repetir",
    "Volume": "Volume",
    "Rating": "Avaliação",
    "Favorite": "Favorito",
    "Favorites": "Favoritos",
    "Queue": "Fila",
    "History": "Histórico",
    "Recent": "Recentes",
    "Popular": "Populares",
    "New": "Novo",
    "Filter": "Filtrar",
    "Sort": "Ordenar",
    "Sort By": "Ordenar por",
    "Details": "Detalhes",
    "View": "Visualizar",
    "Edit": "Editar",
    "Delete": "Excluir",
    "Add": "Adicionar",
    "Remove": "Remover",
    "Create": "Criar",
    "Update": "Atualizar",
    "Save": "Salvar",
    "Cancel": "Cancelar",
    "Close": "Fechar",
    "Apply": "Aplicar",
    "Reset": "Redefinir",
    "Clear": "Limpar",
    "Refresh": "Atualizar",
    "Download": "Baixar",
    "Upload": "Enviar",
    "Import": "Importar",
    "Export": "Exportar",
    "Help": "Ajuda",
    "Options": "Opções",
    "More": "Mais",
    "Show": "Mostrar",
    "Hide": "Ocultar",
    "Enable": "Habilitar",
    "Disable": "Desabilitar",
    "Enabled": "Habilitado",
    "Disabled": "Desabilitado",
    "Active": "Ativo",
    "Inactive": "Inativo",
    "Online": "Online",
    "Offline": "Offline",
    "Available": "Disponível",
    "Public": "Público",
    "Private": "Privado",
    "Required": "Obrigatório",
    "Optional": "Opcional",
    "Default": "Padrão",
    "Advanced": "Avançado",
    "General": "Geral",
    "Unknown": "Desconhecido",
    "Other": "Outro",
    
    # Actions
    "Save Changes": "Salvar Alterações",
    "Saved successfully": "Salvo com sucesso",
    "Deleted successfully": "Excluído com sucesso",
    "Updated successfully": "Atualizado com sucesso",
    "Created successfully": "Criado com sucesso",
    "Failed to save": "Falha ao salvar",
    "Failed to delete": "Falha ao excluir",
    "Failed to update": "Falha ao atualizar",
    "Failed to create": "Falha ao criar",
    "Are you sure?": "Tem certeza?",
    "This action cannot be undone.": "Esta ação não pode ser desfeita.",
    "Confirm Delete": "Confirmar Exclusão",
    "Confirm Action": "Confirmar Ação",
    "Processing...": "Processando...",
    "Please wait...": "Por favor, aguarde...",
    "Operation completed": "Operação concluída",
    "Operation failed": "Operação falhou",
    "Back": "Voltar",
    "Submit": "Enviar",
    
    # Forms
    "Username": "Nome de usuário",
    "Password": "Senha",
    "Email": "E-mail",
    "Comment": "Comentário",
    "Comments": "Comentários",
    "Tags": "Tags",
    "Category": "Categoria",
    "Value": "Valor",
    "Key": "Chave",
    "Select": "Selecionar",
    "File": "Arquivo",
    "Files": "Arquivos",
    "Path": "Caminho",
    "Link": "Link",
    "Image": "Imagem",
    "Images": "Imagens",
    
    # Validation
    "Required field": "Campo obrigatório",
    "Invalid format": "Formato inválido",
    "Invalid email": "E-mail inválido",
    "Field required": "Campo obrigatório",
    
    # Messages
    "No results found": "Nenhum resultado encontrado",
    "No items found": "Nenhum item encontrado",
    "No data available": "Nenhum dado disponível",
    "Empty": "Vazio",
    "Not found": "Não encontrado",
    "Access denied": "Acesso negado",
    "An error occurred": "Ocorreu um erro",
    "Try again": "Tente novamente",
    
    # User
    "Login": "Entrar",
    "Logout": "Sair",
    "Register": "Registrar",
    "Sign In": "Entrar",
    "Sign Out": "Sair",
    "Sign Up": "Cadastrar",
    "Forgot Password": "Esqueceu a senha",
    "Reset Password": "Redefinir senha",
    "Change Password": "Alterar senha",
    "Current Password": "Senha atual",
    "New Password": "Nova senha",
    "Confirm Password": "Confirmar senha",
    "Welcome": "Bem-vindo",
    
    # Admin
    "Administration": "Administração",
    "Overview": "Visão geral",
    "Summary": "Resumo",
    "Report": "Relatório",
    "Reports": "Relatórios",
    "Logs": "Logs",
    "Activity": "Atividade",
    "System": "Sistema",
    "Configuration": "Configuração",
    "Preferences": "Preferências",
    "Permissions": "Permissões",
    "Roles": "Funções",
    "Role": "Função",
    "Administrator": "Administrador",
    "User": "Usuário",
    "Editor": "Editor",
    
    # Music specific
    "Playlist": "Playlist",
    "Add to Playlist": "Adicionar à playlist",
    "Create Playlist": "Criar playlist",
    "Play Now": "Reproduzir agora",
    "Add to Queue": "Adicionar à fila",
    "Now Playing": "Reproduzindo agora",
    "Recently Played": "Reproduzidos recentemente",
    "Most Played": "Mais reproduzidos",
    "Top Rated": "Mais bem avaliados",
    "Album Artist": "Artista do álbum",
    "Track Number": "Número da faixa",
    "Release Date": "Data de lançamento",
    "Play Count": "Reproduções",
    "Last Played": "Última reprodução",
    "Format": "Formato",
    "Quality": "Qualidade",
    "Lyrics": "Letra",
    "Biography": "Biografia",
    "Similar Artists": "Artistas similares",
    "Unknown Artist": "Artista desconhecido",
    "Unknown Album": "Álbum desconhecido",
    
    # Dashboard specific
    "Your plays (last 30 days)": "Suas reproduções (últimos 30 dias)",
    "Your plays per day (last 30d)": "Suas reproduções por dia (últimos 30d)",
    "Recent Activity": "Atividade recente",
    "Total Albums": "Total de álbuns",
    "Total Artists": "Total de artistas",
    "Total Songs": "Total de músicas",
    "Total Plays": "Total de reproduções",
    "Total Duration": "Duração total",
    "Last Updated": "Última atualização",
    "Server Status": "Status do servidor",
    
    # Job related
    "Job": "Tarefa",
    "Job Name": "Nome da tarefa",
    "Running": "Em execução",
    "Completed": "Concluído",
    "Failed": "Falhou",
    "Pending": "Pendente",
    "Cancelled": "Cancelado",
    "Scheduled": "Agendado",
    "Last Run": "Última execução",
    "Next Run": "Próxima execução",
    "Progress": "Progresso",
    
    # Library related
    "Scan Library": "Escanear biblioteca",
    "Library Path": "Caminho da biblioteca",
    "Library Name": "Nome da biblioteca",
    "Music Library": "Biblioteca de músicas",
    "Last Scan": "Última verificação",
    "Add Library": "Adicionar biblioteca",
    "Edit Library": "Editar biblioteca",
    
    # Misc
    "Version": "Versão",
    "License": "Licença",
    "Documentation": "Documentação",
    "Support": "Suporte",
    "Feedback": "Feedback",
    
    # Ok status
    "Ok": "OK",
    "OK": "OK",
    
    # you are admin/editor
    "You are an Admin!": "Você é um Administrador!",
    "You are an Editor!": "Você é um Editor!",
}

def translate_value(english_value, translations):
    """Translate a value using the translation dictionary, with fallback to English."""
    # Try exact match first
    if english_value in translations:
        return translations[english_value]
    
    # Try case-insensitive match
    lower_value = english_value.lower()
    for eng, trans in translations.items():
        if eng.lower() == lower_value:
            return trans
    
    # Return original if no translation found
    return english_value

def create_translated_resx(source_path, target_path, translations, lang_code):
    """Create a translated resx file from the source."""
    tree = ET.parse(source_path)
    root = tree.getroot()
    
    translated_count = 0
    total_count = 0
    
    for data in root.findall('data'):
        value_elem = data.find('value')
        if value_elem is not None and value_elem.text:
            total_count += 1
            original = value_elem.text
            translated = translate_value(original, translations)
            if translated != original:
                translated_count += 1
            value_elem.text = translated
    
    # Write the translated file
    tree.write(target_path, encoding='utf-8', xml_declaration=True)
    
    print(f"  {lang_code}: {translated_count}/{total_count} strings translated")
    return translated_count, total_count

def main():
    base_path = Path(__file__).parent.parent / 'src' / 'Melodee.Blazor' / 'Resources'
    source_file = base_path / 'SharedResources.resx'
    
    languages = {
        'de-DE': GERMAN_TRANSLATIONS,
        'it-IT': ITALIAN_TRANSLATIONS,
        'ja-JP': JAPANESE_TRANSLATIONS,
        'pt-BR': PORTUGUESE_TRANSLATIONS,
    }
    
    print("Translating resource files...")
    print(f"Source: {source_file}")
    print()
    
    for lang_code, translations in languages.items():
        target_file = base_path / f'SharedResources.{lang_code}.resx'
        create_translated_resx(source_file, target_file, translations, lang_code)
    
    print("\nDone!")

if __name__ == '__main__':
    main()
